# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Web Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     # download rep
    - uses: actions/checkout@v3

    # setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
   # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.4.0

    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew 

    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew webTest
